version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pokeapi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # image: ubuntu
    command: python ./pokeapi/aiohttp_pokeapi/main.py
    volumes:
      - .:/pokeapi
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=pokeapi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
