version: '3.9'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pokeapi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # image: ubuntu
    command: python ./pokeapi/aiohttp_pokeapi/main.py
    restart: on-failure
    volumes:
      - .:/pokeapi
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=pokeapi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
